#!/bin/bash
# $Id: preppics,v 1.2 2020/11/23 19:00:47 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/preppics,v $
# $Revision: 1.2 $
# Author C W Fulford.
# Copyright 2019 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: preppics,v 1.2 2020/11/23 19:00:47 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$2;shift 2;;
		-d) set -x;debug=0;shift;;
		-h) hostid=$2;shift 2;;			
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.2 $ $Date: 2020/11/23 19:00:47 $"|awk '{print $1,$3,$6}';exit;;  
		*) files="$files $1";shift;;
	esac
done

config=${config:-/usr/local/etc/${cmd}.cf
[ -r $config ]||{echo "$cmd: Can't find $config";exit 1}
#eval `sed <$config -ne "/^$hostid:/,/^$/{/^[\t ]*[^#].*/p}"`
[ $verbose ] && echo "$cmd: Updating $files"
[ $verbose ] && echo "Adding Artist, Publisher and Copyright"
exiftool -Artist="$(</usr/local/etc/artist)"  -Publisher="$(</usr/local/etc/publisher)"  -Copyright="`/usr/local/etc/copyright`" $files
rm *_original
